### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by kam520c** [09xuanjian/MoveKeyboard#1]
看了readme，还是不清楚怎样使用，请作者指导:（图片链接可能需要复制然后到浏览器粘贴打开）
第一张看起来正常，
[http://ac-3gn36FoG.clouddn.com/614ea68cff68514a35f4.png](url)
然后我点击切换abc，布局就不正常了。请问作者说的自适应view的布局，在哪里可以控制切换数字和字母键盘也一样保存适应布局？
[http://ac-3gn36fog.clouddn.com/d3f19af9490d43f99817.png](url)
[http://ac-3gn36fog.clouddn.com/683a9fdc9e99dbe5d6b5.png](url)
另外，还有一点，如果一开始显示的abc布局，键盘会出现以下奇怪现象。请解答
[http://ac-3gn36fog.clouddn.com/86fca3d92030885fee33.jpeg](url)
 我的布局是这样的，下面那个LinearLayout来addView。
```java
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal">

        <LinearLayout
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:orientation="vertical" />

        <LinearLayout
            android:id="@+id/rootLLayout"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:orientation="vertical" />
    </LinearLayout>
```

使用代码:
```java
 mKeyBoardManage = new KeyboardManage(this, rootLLayout)
                .addEditText(edt, KeyBoardDefinition.INPUTTYPE_ABC);
//                .addEditText(edt, KeyBoardDefinition.INPUTTYPE_NUM, 0, false);
        mKeyBoardManage.showKeyBoard(edt);
```

**Comment by 09xuanjian** [comment]
因为你最外层的LinearLayout,是horizontal了。其实键盘的实现是相对于布局是vertical的，把键盘加载最底下的。你现在相当于把键盘加在了右边的LinearLayout里面了，所有只显示出来一半。
还有就是，如果页面是比较长的，最好用个好像下面一样布局：
<LinearLayout>
     LinearLayout需要orientation="vertical"
    <头部Title的Layout></>
    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="0dp"   重点
        android:layout_weight="1"     重点
        android:scrollbars="none">
        < 你的主要布局 ></>
    </ScrollView>
</LinearLayout>

**Comment by kam520c** [comment]
你好，我看见你的readme上写键盘可以嵌入在activity里面，也可以嵌入到某个View里面。
所以我的是镶嵌在rootLLayout这个view里面的。对的需求就是把键盘加在右边的LinearLayout里。
如此图：http://ac-3gn36FoG.clouddn.com/614ea68cff68514a35f4.png
点击切换后应该是此图：http://ac-3gn36fog.clouddn.com/86fca3d92030885fee33.jpeg
对于keyboard来说，rootLLayout这个应该就是最外层的view吧？我最开始加载的时候，就像第一张图片，布局是正确的，就是需要那样的效果，只是切换英文字母时，布局自动变化，不知道是否外层的view自动获取了外面activity的才导致宽度变化了？

**Comment by 09xuanjian** [comment]
哦，可能我定义的嵌入某个View定义有问题。嵌入某个View，其实一般是用于我们出现一些弹框的View里面又需要自定义的键盘。如果你直接半屏使用，ABC那些布局是用问题的，太小了，不能容下这么大一个键盘。对于keyboard来说，rootLLayout是最外层的view。当初写这个键盘，都是基于整个屏幕使用的。如果半边屏幕，这个当时没有做相关的适配。

**Comment by kam520c** [comment]
好的，谢谢你。看来只能自己实现这个功能了。
